feat: финальный проект Спринта 9
rs-popov/java-filmorate pull request #2
Opened 2022-06-19 09:00 UTC by rs-popov

Добавлено решение финального проекта Спринта 9

2022-06-20 10:39 UTC, Fleaman777 requested changes

2022-06-20 10:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film findFilm(@PathVariable Optional<Integer> id) {
интересный подход для айдишника,

но здесь особо нет смысла айдишник делать Optional, можно сказать лишее усложнение, т.к. даже если его не будет, то можно просто проверить null(в случае Integer) он или 0 (в случае int),
или если даже он 0, то просто передать его дальше в сервис -> сторадже, а потом из мапы мы ничего не получим, т.к. фильма с таким айди в нее не сохранено
 
так же можно проставить дефолтное значение, что бы например точно не нарваться на момент, когда у фильма был айди 0, а мы его проигнорили

2022-06-20 10:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        filmStorage.updateFilm(film);
Правильный подход, когда контроллер напрямую не взаимодействует с FileStorage.
вся необходимая логика (вызовы методов файл стореджа для сохранения, обновления, получения и др бизнес логика) делается через соответствующие методы сервиса,
например в сервисе будет метод updateFilm(film), и в этом методе будет использоваться метод filmStorage.updateFilm(film)

это замечание относится ко всем похожим местам в 2х контроллерах

2022-06-20 10:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FriendsController.java
> +                .collect(Collectors.toList());
т.к. контроллер выполняет работу только по получению реквестов и отправки респонсов, а всю остальную логику делают сервиса, лучше этот стрим перенести в метод юзер севриса

2022-06-20 10:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/LikesController.java
> +    public Collection<Film> findPopular(@RequestParam Optional<Integer> count) {
здесь тоже можно не делать Optional

2022-06-20 10:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    }
конструктор можно сделать через ломбок аннотацию, а Set с лайкми проинициализировать сразу 
private Set<Integer> likes= new HashSet<>()

аналагично с юзером

2022-06-20 10:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted((f0, f1) -> f1.getLikes().size()-f0.getLikes().size())
для улучшения разделения ответственности, компаратор можно вынести в отдельный метод,
или можно классом Film симплементировать интерфейс Comparable, тогда можно будет просто использовать метод .sorted() без аргумента

2022-06-20 10:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .collect(Collectors.toList());
хорошее решение со стримом, выглядит компактно и аккуратно

2022-06-20 10:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Film findFilm(int id);
более привычное название было бы getFilmById(id)

у юзера аналагично

2022-06-20 10:39 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        }
у нас в сторедже уже есть проверка, которая позволет узнать, есть ли фильм в сторедже или нет, 
можно оставить только одну

2022-06-21 01:13 UTC, rs-popov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        }
Убрал проверки из сервисов

2022-06-21 01:14 UTC, rs-popov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    Film findFilm(int id);
Изменил названия методо на getFilmById(id) и getUserById(id)

2022-06-21 01:14 UTC, rs-popov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted((f0, f1) -> f1.getLikes().size()-f0.getLikes().size())
Сделал сортировку через имплементацию интерфейса Comparable

2022-06-21 01:16 UTC, rs-popov commented on src/main/java/ru/yandex/practicum/filmorate/controller/LikesController.java
> +    public Collection<Film> findPopular(@RequestParam Optional<Integer> count) {
Узменил findPopular(@RequestParam Optional<Integer> count) на findPopular(@RequestParam(required = false) Integer count) с последующей проверкой на null

2022-06-21 01:22 UTC, rs-popov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FriendsController.java
> +                .collect(Collectors.toList());
Перенес метод в UserService

2022-06-21 01:23 UTC, rs-popov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film findFilm(@PathVariable Optional<Integer> id) {
Убрал Optional

2022-06-21 03:13 UTC, rs-popov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        filmStorage.updateFilm(film);
Перенес всю логику в классы сервиса

2022-06-21 03:41 UTC, rs-popov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    }
Сделал конструктор через аннотации ломбок

2022-06-22 01:07 UTC, merged