feat: финальное задание спринта 11
rs-popov/java-filmorate pull request #3
Opened 2022-07-02 08:28 UTC by rs-popov

2022-07-04 12:50 UTC, Fleaman777 requested changes

2022-07-04 12:50 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +            throw new InternalErrorException("");
можно добавить инфу в эксепшен, что пошло не так

2022-07-04 12:50 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenresDAOImpl.java
> +    public HashSet<Genre> getGenresByFilmId(int id) {
метод может возвращать более широкий тип Set

2022-07-04 12:50 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDAOImpl.java
> +                (rs, num) -> rs.getInt("FRIEND_ID"), resultSet.getInt("USER_ID")));
хорошо было бы вынести в отдельную перменнею или в метод логику, которая передается при создании ХэшСета 
это улучшило бы восприятие кода,

2022-07-04 12:50 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/impl/UserDAOImplTest.java
> +}
хорошие тесты, но еще нужно добавить для других ДАО классов, 
т.к по заданию необходимо, что бы все публичные методы хранилища были покрыты тестами.

2022-07-05 08:24 UTC, rs-popov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/GenresDAOImpl.java
> +    public HashSet<Genre> getGenresByFilmId(int id) {
Исправил HashSet на Set

2022-07-05 08:42 UTC, rs-popov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/UserDAOImpl.java
> +                (rs, num) -> rs.getInt("FRIEND_ID"), resultSet.getInt("USER_ID")));
Вынес логику в метод HashSet<Integer> getFriendsByUserId(int id)

2022-07-05 08:44 UTC, rs-popov commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +            throw new InternalErrorException("");
исправил

2022-07-05 09:44 UTC, rs-popov commented on src/test/java/ru/yandex/practicum/filmorate/storage/impl/UserDAOImplTest.java
> +}
Добавил тесты для жанров и рейтингов MPA

2022-07-07 01:40 UTC, merged